version: 2

sources:
  - name: public
    description: "Raw data source for Telegram messages"
    tables:
      - name: telegram_messages
        description: "Raw Telegram messages table"

models:
  - name: messages_with_media
    description: "Messages that contain media files."
  - name: youtube_activity_summary
    description: "Summary of YouTube links shared per channel."
